version: "3.4"

services:

    mysql:
        image: mysql
        container_name: mysql        
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: myUserPass
          MYSQL_DATABASE: agenda-petshop
          MYSQL_USER: myUser
          MYSQL_PASSWORD: myUser
        networks: 
          - alura-workspace

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
          - 8088:80
        environment:
          PMA_HOST: db
          MYSQL_ROOT_PASSWORD: myUserPass  
        networks: 
          - alura-workspace      
        
    # adminer:
    #     image: adminer
    #     restart: always
    #     ports:
    #         - 8082:8080

    # mongo:
    #     image: mongo:4.0.5
    #     container_name: mongo
    #     hostname: mongo-db
    #     expose:
    #       - "27017"
    #     ports:
    #       - "27017:27017"
    #     networks: 
    #       - alura-workspace
    #     command: --bind_ip_all --smallfiles
    #     volumes:
    #       - ./mongo-db:/data
        
    # mongoclient:
    #     image: mongoclient/mongoclient:2.2.0
    #     container_name: mongoclient
    #     ports:
    #         - 3020:3020
    #     networks: 
    #         - alura-workspace
    #     environment:
    #         MONGO_URL: "mongodb://mongo:27017"
    #         PORT: 3020
    #     expose:
    #         - "3020"
    
networks:
    alura-workspace:
        driver: bridge
        external: true